import importlib
import json
import inspect
from toolbox import get_conf

def generate_markdown():
    # Load Core Functions
    import core_functional
    importlib.reload(core_functional)
    core_funcs = core_functional.get_core_functions()

    # Load Crazy Functions (Plugins)
    try:
        from crazy_functional import get_crazy_functions
        crazy_funcs = get_crazy_functions()
    except Exception as e:
        print(f"Error loading crazy functions: {e}")
        crazy_funcs = {}

    lines = []
    lines.append("# Agent Skills Index")
    lines.append("")
    lines.append("This file is automatically generated by `gen_skill_md.py`. It lists all available functions and plugins.")
    lines.append("")

    lines.append("## Core Functions (Prompt Templates)")
    lines.append("| Function Name | Description |")
    lines.append("| :--- | :--- |")

    for name, meta in core_funcs.items():
        description = ""
        if "Prefix" in meta:
            # Clean up the prefix to make it a readable description
            prefix = meta["Prefix"].strip()
            # Take the first non-empty line
            lines_in_prefix = [l.strip() for l in prefix.split('\n') if l.strip()]
            if lines_in_prefix:
                description = lines_in_prefix[0]
                # If it's too long, truncate
                if len(description) > 100:
                    description = description[:97] + "..."

        # Escape pipe characters for Markdown table
        description = description.replace("|", "\|").replace("\n", " ")
        lines.append(f"| {name} | {description} |")

    lines.append("")
    lines.append("## Crazy Functions (Plugins)")
    lines.append("| Function Name | Group | Description |")
    lines.append("| :--- | :--- | :--- |")

    # Sort keys for consistent output
    sorted_crazy_keys = sorted(crazy_funcs.keys())

    for name in sorted_crazy_keys:
        meta = crazy_funcs[name]
        group = meta.get("Group", "Unknown")
        info = meta.get("Info", "No description available")

        # Clean up
        group = group.replace("|", "\|")
        info = info.replace("|", "\|").replace("\n", " ")

        lines.append(f"| {name} | {group} | {info} |")

    content = "\n".join(lines)

    with open("SKILL.md", "w", encoding="utf-8") as f:
        f.write(content)

    print(f"Generated SKILL.md with {len(core_funcs)} core functions and {len(crazy_funcs)} plugins.")

if __name__ == "__main__":
    generate_markdown()
